# Generated by Django 4.0.3 on 2022-04-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0008_alter_song_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='song',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='song',
            name='tags',
        ),
    ]
