# Generated by Django 4.0.3 on 2022-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0011_alter_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
